### PR TITLE
fixes logic for available workers. otherwise you get a nil error

### PR DESCRIPTION
**Pull request by abduld**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Found some fixes!

_P.S. share your ideas, feedbacks or issues with us at https://github.com/fixmie/feedback (this message will be removed after the beta stage)._

**Comment by aschuh703** [comment]
Abdul, this pull request changes used types but does not change the foundational struct type and subsequently fails. Server currently builds without this pull. I do not understand the need for the pull request.

Please advise.

**Review by ghost — COMMENTED** [review]
Found some fixes!

_P.S. share your ideas, feedbacks or issues with us at https://github.com/fixmie/feedback (this message will be removed after the beta stage)._

**Comment by abduld** [comment]
> Abdul, this pull request changes used types but does not change the foundational struct type and subsequently fails. Server currently builds without this pull. I do not understand the need for the pull request.
> 
> Please advise.

how does the available workers work? why is there a decrement when a client subscribes and an increment when the worker ends? how are those related since one executes on the client and one on the server. also the style used in not the suggested style for go (for one pointers are not good). look at https://github.com/golang/go/wiki/CodeReviewComments, https://golang.org/doc/effective_go.html, https://rakyll.org/style-packages/ . I have made changes to the pull request, but I do not think the available workers logic is correct

**Pull request merged**
